### ISSUE TITLE
Uncaught Invariant Violation: ShadowWrapper.render()

### ISSUE THREAD

**Issue by anton6** [matt-landers/react-shadow-wrapper#1]
Trying to render basic scenario:

```
import ShadowWrapper from 'react-shadow-wrapper';

const Main = () => {
  return (
    <ShadowWrapper>
      <div>11111</div>
      <div>222222</div>
    </ShadowWrapper>
  );
};
```

But getting the following error:

Uncaught Invariant Violation: ShadowWrapper.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

I am using "react": "^15.6.0"

Anyone else came across this issue?

Works if I do one element though:

```
import ShadowWrapper from 'react-shadow-wrapper';

const Main = () => {
  return (
    <ShadowWrapper>
      <div>11111</div>
    </ShadowWrapper>
  );
};
```

**Comment by matt-landers** [comment]
@anton6 Unfortunately, this solution won't work in React 15. The ability to return arrays was introduced in React 16.

**Comment by anton6** [comment]
Ah I see, ok thanks for quick response. I thought this is similar to react-dot-fragment which I think has react 15 support.
